apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodweather-app-deploy
  labels:
    name: goodweather-app-deploy
    app: tfg-goodweather-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: goodweather-app-pod
      app: tfg-goodweather-app
  template:
    metadata:
      name: goodweather-app-pod
      labels:
        name: goodweather-app-pod
        app: tfg-goodweather-app
    spec:
      containers:
        - name: goodweather-app
          image: aarontas8/goodweather:app-1a37147f6043449a3dd54243956c48d44d80e091
          ports:
          - containerPort: 80
