apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodweather-app-deploy
  labels:
    name: goodweather-app-deploy
    app: tfg-goodweather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: goodweather-app-pod
      app: tfg-goodweather-app
  template:
    metadata:
      name: goodweather-app-pod
      labels:
        name: goodweather-app-pod
        app: tfg-goodweather-app
    spec:
      containers:
        - name: goodweather-app
          image: aarontas8/goodweather:app-ec9977f2e0bc5e9c42a608497d4f39e07429afec
          ports:
          - containerPort: 80
