apiVersion: v1
kind: Pod
metadata:
  name: goodweather-app-pod
  labels:
    name: goodweather-app-pod
    app: tfg-goodweather-app
spec:
 containers:
  - name: goodweather-app
    image: aarontas8/goodweather:app-daec155ca9662b1907580041a0acb73687644a82
    ports:
     - containerPort: 80
