apiVersion: v1
kind: Service
metadata:
  name: goodweather-service
  labels:
        name: goodweather-app-pod
        app: tfg-goodweather-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
        name: goodweather-app-pod
        app: tfg-goodweather-app
  