apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodweather-app-deploy
  labels:
    name: goodweather-app-deploy
    app: tfg-goodweather-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: goodweather-app-pod
      app: tfg-goodweather-app
  template:
    metadata:
      name: goodweather-app-pod
      labels:
        name: goodweather-app-pod
        app: tfg-goodweather-app
    spec:
      containers:
        - name: goodweather-app
          image: aarontas8/goodweather:app-1b5a868caa4281740e64243ae55fc6fbcc1bdd4e
          ports:
          - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
