apiVersion: v1
kind: Service
metadata:
  name: goodweather-service
  labels:
        name: goodweather-app-pod
        app: tfg-goodweather-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30006
  selector:
        name: goodweather-app-pod
        app: tfg-goodweather-app
  