apiVersion: v1
kind: Pod
metadata:
  name: goodweather-app-pod
  labels:
    name: goodweather-app-pod
    app: tfg-goodweather-app
spec:
 containers:
  - name: goodweather-app
    image: aarontas8/goodweather:app-10cf244e076ec0d3ab49622ac1f132efd961cae7
    ports:
     - containerPort: 80
