apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: redis-deploy
    app: tfg-goodweather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: tfg-goodweather-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: tfg-goodweather-app
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
